apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  namespace: um-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      containers:
      - name: um-container
        image: us-central1-docker.pkg.dev/um-project-459607/um-container-repo/um-container:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9900
          name: nsp
        - containerPort: 9000
          name: admin
        readinessProbe:
          tcpSocket:
            port: 9900
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 9900
          initialDelaySeconds: 180
          periodSeconds: 20
          failureThreshold: 5
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
            ephemeral-storage: "512Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "1Gi"
        volumeMounts:
        - name: um-data
          mountPath: /opt/um/UniversalMessaging/server/umserver/data
        - name: um-config
          mountPath: /opt/um/UniversalMessaging/server/umserver/bin/nserver.conf
          subPath: nserver.conf
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m -verbose:gc"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        workingDir: /opt/um/UniversalMessaging/server/umserver/bin
      volumes:
      - name: um-data
        persistentVolumeClaim:
          claimName: um-data-pvc
      - name: um-config
        configMap:
          name: um-config
          items:
          - key: nserver.conf
            path: nserver.conf
