apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  namespace: um-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      containers:
        - name: um-container
          image: us-central1-docker.pkg.dev/um-project-459607/um-container-repo/um-container
          ports:
            - containerPort: 9900
