apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  namespace: um-deployment
spec:
  replicas: 2 # Reduced to 2 to ease resource pressure
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      containers:
      - name: um-container
        image: us-central1-docker.pkg.dev/um-project-459607/um-container-repo/um-container:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9900
          name: nsp
        - containerPort: 9000 # For admin console (optional)
          name: admin
        readinessProbe:
          tcpSocket: # Reverted to tcpSocket as /rest/monitoring/status may not be supported
            port: 9900
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 9900
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 3
        resources:
          requests:
            cpu: "50m" # Reduced to ease scheduling
            memory: "256Mi" # Reduced
          limits:
            cpu: "250m"
            memory: "512Mi"
        volumeMounts:
        - name: um-data
          mountPath: /home/vkraft/softwareAG3/UniversalMessaging/server/umserver/data
        - name: um-config
          mountPath: /home/vkraft/softwareAG3/UniversalMessaging/server/umserver/bin/nserver.conf
          subPath: nserver.conf
      volumes:
      - name: um-data
        persistentVolumeClaim:
          claimName: um-data-pvc
      - name: um-config
        configMap:
          name: um-config
          items:
          - key: nserver.conf
            path: nserver.conf