apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: um-data-pvc
  namespace: um-deployment
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: filestore-rwx
