apiVersion: v1
kind: Service
metadata:
  name: deployment-1-service
  namespace: um-deployment
  labels:
    app: deployment-1
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: deployment-1
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: nsp
    protocol: TCP
    port: 9900
    targetPort: 9900
  - name: admin
    protocol: TCP
    port: 9000
    targetPort: 9000